
Students = [
    {
        "id":1,
        "FirstName":"Bayizere",
        "LastName":"Marius",
        "Email":"bayizeremarius119@gmail",
        "PhoneNumber":"078888888",
        "Gender":"Male",
        "Nationality":"Rwandan"
    },
        {
        "id":2,
        "FirstName":"Abijuru",
        "LastName":"Raissa",
        "Email":"raissabijuru@gmail",
        "PhoneNumber":"078888882",
        "Gender":"Famale",
        "Nationality":"Rwandan"
    },
        {
        "id":3,
        "FirstName":"Iradukunda",
        "LastName":"Feza",
        "Email":"feza@gmail",
        "PhoneNumber":"078882888",
        "Gender":"Famile",
        "Nationality":"Rwandan"
    },
        {
        "id":4,
        "FirstName":"byiringiro",
        "LastName":"Danny",
        "Email":"byiringiro@gmail",
        "PhoneNumber":"078888868",
        "Gender":"Male",
        "Nationality":"Rwandan"
    }
    ,
        {
        "id":5,
        "FirstName":"Shema",
        "LastName":"Rogers",
        "Email":"shema@gmail",
        "PhoneNumber":"078888988",
        "Gender":"Male",
        "Nationality":"Rwandan"
    },
        {
        "id":6,
        "FirstName":"Manishimwe",
        "LastName":"Eric",
        "Email":"eric@gmail",
        "PhoneNumber":"078881888",
        "Gender":"Male",
        "Nationality":"Rwandan"
    },
        {
        "id":7,
        "FirstName":"Mugisha",
        "LastName":"Eric",
        "Email":"mugisha@gmail",
        "PhoneNumber":"078888880",
        "Gender":"Male",
        "Nationality":"Rwandan"
    }
]